#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("droidApp.Resource", IsApplication=true)]

namespace droidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
			mDroidCore.Resource.String.library_name = droidApp.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add20 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Excel48 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Folder48 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_tab_about = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_tab_about_selected = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_tab_about_unselected = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_tab_explorer = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_tab_explorer_selected = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_tab_explorer_unselected = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Image48 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int PDF48 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int PowerPoint48 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Undefined48 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Word48 = 2130837518;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int FileEntryDetailTextItem = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int FileEntryImageItem = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int FileEntryTextItem = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout1 = 2131034113;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FileEntryListItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Home = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
